repos:
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # only messages
            "-sn", # dont display score
            "--rcfile=.pylintrc", #link to your config file
            "--load-plugins=pylint.extensions.docparams" #load an extension
          ]